### ISSUE TITLE
Adventure Mode Compatibility

### ISSUE THREAD

**Issue by MCYCShadow** [LCLPYT/illusory-walls#4] opened 2024-02-29 18:45 UTC
Hey, having fun using the mod just for what it is for, making secret rooms etc.
I'm having the issue of it not detecting block hits in adventure mode.

Would be nice to make it use able there as well.
Additionally I set a +1 for options that make the walls reappear.
Otherweise, hope you doing good and may come back for some updates in the future. 

Cheers

**Comment by LCLPYT** [comment] 2024-02-29 18:54
Hi @MCYCShadow,
thank you for using the mod.

I am already aware of the adventure mode issue (#2).
It is caused by the vanilla behaviour, as you cannot hit blocks in adventure mode.
That can be fixed rather easily though.

As for the suggenstion in #1 , this behaviour is already finished.
Right now, it is only missing a graphical interface to be configured...

Sadly I am not currently motivated to develop this mod. 
But, I will definitely put this on my todo list, thank you for reaching out!

**Comment by LCLPYT** [comment] 2024-04-18 17:20
This is now fixed in version 0.2.0

**Closed as completed by LCLPYT** 2024-04-18 17:20 UTC
Labels: enhancement

**Comment by MCYCShadow** [comment] 2024-06-04 21:17
Heyo, just wanted to drop by and say thanks for your work.
